version: '3.8'

services:
  kill-the-newsletter:
    image: node:latest
    container_name: kill-the-newsletter
    working_dir: /app
    ports:
      - "8000:8000"
      - "2525:2525"
    volumes:
      - /srv/kill-the-newsletter/certificates:/root/.local/share/caddy/certificates
    command: npm start
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: production
      EMAIL_DOMAIN: "ktn.unixmail.org"
      ISSUE_REPORT: "mailto:j@unixmail.org"
      WEB_PORT: 8000
      EMAIL_PORT: 2525
      BASE_URL: "https://ktn.unixmail.org:8000"
      TUNNEL: "ktn.unixmail.org"
    build:
      context: .
      dockerfile: Dockerfile
